In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/1_linear_reg/Exercise/canada_per_capita_income.csv')

In [3]:
df.head

<bound method NDFrame.head of     year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997          

In [4]:
df.columns

Index(['year', 'per capita income (US$)'], dtype='object')

In [5]:
X = df['year'].values.reshape(-1,1)
y = df['per capita income (US$)'].values
reg = linear_model.LinearRegression()
reg.fit(X,y)
reg.predict([[2011]])

array([33832.50841741])

In [6]:
reg.coef_

array([828.46507522])

In [7]:
reg.intercept_

-1632210.7578554575

In [8]:
2011*828.46507522+-1632210.7578554575

33832.50841196254

In [10]:
import pickle



In [15]:
with open('reg_pickel','wb') as f:
    pickle.dump(reg,f)

In [19]:
with open('reg_pickel','rb') as f:
    rp=pickle.load(f)

In [20]:
rp.predict([[2011]])

array([33832.50841741])

In [22]:
rp.intercept_

-1632210.7578554575

In [23]:
rp.coef_

array([828.46507522])

In [25]:
pip install joblib


Note: you may need to restart the kernel to use updated packages.


In [29]:
import joblib

In [30]:
joblib.dump(reg,'reg_joblib')
rj=joblib.load('reg_joblib')

In [31]:
rj.predict([[2021]])

array([42117.15916964])

In [ ]:
#by using joblib it hellps to read the large data work like a human brain 